version: '2'
services:
  pretalx:
    image: pretalx/standalone:latest
    container_name: pretalx
    restart: unless-stopped
    depends_on: 
      - redis
      - db
    ports:
      - "80:80"
    volumes: 
      - ./conf/pretalx.cfg:/etc/pretalx/pretalx.cfg:ro
      - pretalx-data:/data
    labels:
       traefik.docker.network: "pretalxdocker"
       traefik.enable: "true"


  db:
    image: mysql:5
    container_name: pretalx-db
    restart: unless-stopped
    volumes:
      - pretalx-db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: pretalx
      MYSQL_USER: pretalx
      MYSQL_PASSWORD: veryunsecureplschange
      MYSQL_RANDOM_ROOT_PASSWORD: "1"

  redis:
    image: redis:latest
    container_name: pretalx-redis
    restart: unless-stopped
    volumes: 
      - pretalx-redis:/data


volumes:
  pretalx-db:
  pretalx-data:
  pretalx-redis:

  
