version: '2'

services:
    pretalx:
        image: pretalx
        hostname: pretalx_core
        container_name: pretalx_core
        build:
          context: pretalx
        volumes:
           - $PWD/conf/pretalx.cfg:/src/pretalx.cfg:ro 
           - $PWD/volumes/pretalx-data:/data:rw
           - /src/static.dist
        links:
           - db:db
           - redis:redis
           - smtp:smtp
        depends_on:
           - db

    pretalx_celery:
        image: pretalx
        hostname: pretalx_celery
        container_name: pretalx_celery
        user: pretalx
        build:
          context: pretalx
        volumes:
           - $PWD/docker-celery-entrypoint.sh:/docker-celery-entrypoint.sh:ro 
           - $PWD/conf/pretalx.cfg:/src/pretalx.cfg:ro 
           - $PWD/volumes/pretalx-data:/data:rw
        volumes_from:
           - pretalx:rw
        links:
           - db:db
           - redis:redis
           - smtp:smtp
        depends_on:
           - db
           - redis
           - pretalx
        entrypoint: /docker-celery-entrypoint.sh

    nginx:
        image: nginx
        hostname: nginx
        container_name: pretalx_nginx
        ports:
            - 80:80
# DO NOT USE WITHOUT SSL IN PRODUCTION
#            - 443:443
        volumes:
            - $PWD/conf/nginx/conf.d:/etc/nginx/conf.d:ro
            - $PWD/conf/ssl/cert.pem:/cert.pem:ro
            - $PWD/conf/ssl/key.pem:/key.pem:ro
            - $PWD/volumes/nginx-data:/var/log/nginx:rw
            - $PWD/volumes/pretalx-data/media/:/media:ro
        links:
            - pretalx:pretalx
        volumes_from:
            - pretalx:ro
    db:
       image: mysql
       hostname: mysql
       container_name: pretalx_mysql
       command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
       volumes:
         - $PWD/conf/mysql-password.secret:/run/secrets/mysql-password:ro
         - $PWD/conf/pretalx-password.secret:/run/secrets/pretalx-password:ro
         - $PWD/volumes/mysql-data:/var/lib/mysql:rw
       environment:
         - MYSQL_DATABASE=pretalx
         - MYSQL_USER=pretalx
         - MYSQL_PASSWORD_FILE=/run/secrets/pretalx-password
         - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-password
    smtp:
        container_name: pretalx_smtp
        image: tecnativa/smtp-sink  
            
    redis:
        container_name: pretalx_redis
        image: redis 
        volumes:
          - $PWD/volumes/redis-data:/data:rw
